// <auto-generated />
using System;
using Factory.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Factory.DAL.Migrations
{
    [DbContext(typeof(FactDdContext))]
    [Migration("20250309115955_Apply All")]
    partial class ApplyAll
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Factory.DAL.Models.Auth.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteRequestedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDarkModeEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMFAEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastBackupDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePictureUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Factory.DAL.Models.Documentation.Documentation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Documentation");
                });

            modelBuilder.Entity("Factory.DAL.Models.Finance.FinancialRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_FinancialRecords_Date");

                    b.ToTable("FinancialRecords", (string)null);
                });

            modelBuilder.Entity("Factory.DAL.Models.Home.ContactUs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ContactUs");
                });

            modelBuilder.Entity("Factory.DAL.Models.Home.Partner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Partners", (string)null);
                });

            modelBuilder.Entity("Factory.DAL.Models.Home.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AgentEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AgentPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("int");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasGarage")
                        .HasColumnType("bit");

                    b.Property<bool>("HasPool")
                        .HasColumnType("bit");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsFurnished")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ListedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhotoUrls")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SquareFootage")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Property");
                });

            modelBuilder.Entity("Factory.DAL.Models.Home.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FacebookLink")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("InstagramLink")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsHidden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LinkedInLink")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfileImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TwitterLink")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("YouTubeLink")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("TeamMember");
                });

            modelBuilder.Entity("Factory.DAL.Models.OnBoarding.ITSetupModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AccessGranted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EmailSetup")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("HardwareProvisioned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OnboardingProcessId")
                        .HasColumnType("int");

                    b.Property<bool>("SoftwareInstalled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("OnboardingProcessId")
                        .IsUnique();

                    b.ToTable("ITSetupModule");
                });

            modelBuilder.Entity("Factory.DAL.Models.OnBoarding.OnboardingProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("OnboardingProcess");
                });

            modelBuilder.Entity("Factory.DAL.Models.OnBoarding.OrientationModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CompanyOrientationCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DepartmentOrientationCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("FirstWeekCheckInCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("MentorAssigned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OnboardingProcessId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OnboardingProcessId")
                        .IsUnique();

                    b.ToTable("OrientationModule");
                });

            modelBuilder.Entity("Factory.DAL.Models.OnBoarding.PreboardingModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("BackgroundCheckCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ContractSigned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("DocumentsReceived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OnboardingProcessId")
                        .HasColumnType("int");

                    b.Property<bool>("WelcomeEmailSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("OnboardingProcessId")
                        .IsUnique();

                    b.ToTable("PreboardingModule");
                });

            modelBuilder.Entity("Factory.DAL.Models.OnBoarding.TrainingModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ComplianceTraining")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OnboardingProcessId")
                        .HasColumnType("int");

                    b.Property<bool>("SecurityTraining")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("SkillsTraining")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("SystemsTraining")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("OnboardingProcessId")
                        .IsUnique();

                    b.ToTable("TrainingModule");
                });

            modelBuilder.Entity("Factory.DAL.Models.OrderList.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CustomerReference")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FinishDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("bit");

                    b.Property<string>("JobNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double?>("Rank")
                        .HasPrecision(18, 2)
                        .HasColumnType("float(18)");

                    b.Property<string>("SelectedMachines")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("TotalLM")
                        .HasPrecision(18, 2)
                        .HasColumnType("float(18)");

                    b.Property<double>("TotalSQM")
                        .HasPrecision(18, 2)
                        .HasColumnType("float(18)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("Factory.DAL.Models.OrderList.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveredBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double>("Height")
                        .HasPrecision(18, 2)
                        .HasColumnType("float(18)");

                    b.Property<bool>("IsDelivered")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<double?>("Rank")
                        .HasPrecision(18, 2)
                        .HasColumnType("float(18)");

                    b.Property<double>("SQM")
                        .HasPrecision(18, 2)
                        .HasColumnType("float(18)");

                    b.Property<double?>("StepHeight")
                        .HasPrecision(18, 2)
                        .HasColumnType("float(18)");

                    b.Property<double?>("StepWidth")
                        .HasPrecision(18, 2)
                        .HasColumnType("float(18)");

                    b.Property<double>("TotalLM")
                        .HasPrecision(18, 2)
                        .HasColumnType("float(18)");

                    b.Property<double>("Width")
                        .HasPrecision(18, 2)
                        .HasColumnType("float(18)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("Factory.DAL.Models.Permission.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IconClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Modules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IconClass = "bi bi-shield-lock",
                            Name = "Permission Management",
                            Url = "/Users/Index"
                        },
                        new
                        {
                            Id = 2,
                            IconClass = "bi bi-people",
                            Name = "User Management",
                            Url = "/Auth/Index"
                        },
                        new
                        {
                            Id = 3,
                            IconClass = "bi bi-person-badge",
                            Name = "Role Management",
                            Url = "/Role/Index"
                        },
                        new
                        {
                            Id = 4,
                            IconClass = "bi bi-box-seam",
                            Name = "Warehouse Management",
                            Url = "/Warehouse/Index"
                        },
                        new
                        {
                            Id = 5,
                            IconClass = "bi bi-cart",
                            Name = "Orders",
                            Url = "/Order/Index"
                        },
                        new
                        {
                            Id = 6,
                            IconClass = "bi bi-cash",
                            Name = "Payroll",
                            Url = "/Payroll/Index"
                        },
                        new
                        {
                            Id = 7,
                            IconClass = "bi bi-gear",
                            Name = "Settings",
                            Url = "/Settings/Index"
                        },
                        new
                        {
                            Id = 8,
                            IconClass = "bi bi-cash-stack",
                            Name = "Financial",
                            Url = "/Accountant/Index"
                        },
                        new
                        {
                            Id = 9,
                            IconClass = "bi bi-person-plus",
                            Name = "Onboarding",
                            Url = "/Onboarding/Index"
                        },
                        new
                        {
                            Id = 10,
                            IconClass = "bi bi-person-dash",
                            Name = "Offboarding",
                            Url = "/Offboarding/Index"
                        },
                        new
                        {
                            Id = 11,
                            IconClass = "bi bi-briefcase",
                            Name = "HR Management",
                            Url = "/HR/Index"
                        },
                        new
                        {
                            Id = 12,
                            IconClass = "bi bi-graph-up",
                            Name = "Performance Management",
                            Url = "/Performance/Index"
                        },
                        new
                        {
                            Id = 13,
                            IconClass = "bi bi-person-circle",
                            Name = "Employee Self-Service",
                            Url = "/ESS/Index"
                        },
                        new
                        {
                            Id = 14,
                            IconClass = "bi bi-laptop",
                            Name = "IT Service Desk",
                            Url = "/ITService/Index"
                        },
                        new
                        {
                            Id = 15,
                            IconClass = "bi bi-key",
                            Name = "Access Control",
                            Url = "/AccessControl/Index"
                        },
                        new
                        {
                            Id = 16,
                            IconClass = "bi bi-kanban",
                            Name = "Project Management",
                            Url = "/Project/Index"
                        },
                        new
                        {
                            Id = 17,
                            IconClass = "bi bi-lightning",
                            Name = "Workflow Automation",
                            Url = "/Workflow/Index"
                        },
                        new
                        {
                            Id = 18,
                            IconClass = "bi bi-headset",
                            Name = "Customer Support",
                            Url = "/Support/Index"
                        },
                        new
                        {
                            Id = 19,
                            IconClass = "bi bi-person-lines-fill",
                            Name = "CRM",
                            Url = "/CRM/Index"
                        },
                        new
                        {
                            Id = 20,
                            IconClass = "bi bi-bar-chart-line",
                            Name = "Analytics & Reporting",
                            Url = "/Reports/Index"
                        });
                });

            modelBuilder.Entity("Factory.DAL.Models.Permission.PermissionTyepe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("PermissionTyepe", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Create"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Read"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Update"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Delete"
                        });
                });

            modelBuilder.Entity("Factory.DAL.Models.Permission.RolePermission", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId", "ModuleId");

                    b.HasIndex("ModuleId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions", (string)null);
                });

            modelBuilder.Entity("Factory.DAL.Models.Permission.SubModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Controller")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IconClass")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("SubModules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = "index",
                            Controller = "PermissionManagement",
                            IconClass = "bi-shield-lock",
                            ModuleId = 1,
                            Name = "Permission Management",
                            Title = "Manage Permissions"
                        },
                        new
                        {
                            Id = 2,
                            Action = "AssignPermissions",
                            Controller = "PermissionManagement",
                            IconClass = "bi-person-check",
                            ModuleId = 1,
                            Name = "Assign Permission",
                            Title = "Assign Permissions"
                        },
                        new
                        {
                            Id = 3,
                            Action = "index",
                            Controller = "Module",
                            IconClass = "bi-puzzle",
                            ModuleId = 1,
                            Name = "Modules Management",
                            Title = "Modules Management"
                        },
                        new
                        {
                            Id = 4,
                            Action = "Index",
                            Controller = "SubModule",
                            IconClass = "bi-puzzle-fill",
                            ModuleId = 1,
                            Name = "Sub Modules Management",
                            Title = "Sub Modules Management"
                        },
                        new
                        {
                            Id = 5,
                            Action = "index",
                            Controller = "Auth",
                            IconClass = "bi-people",
                            ModuleId = 2,
                            Name = "User Management",
                            Title = "User Management"
                        },
                        new
                        {
                            Id = 6,
                            Action = "index",
                            Controller = "Role",
                            IconClass = "bi-person-badge",
                            ModuleId = 3,
                            Name = "Role Management",
                            Title = "Role Management"
                        },
                        new
                        {
                            Id = 7,
                            Action = "index",
                            Controller = "Warehouse",
                            IconClass = "bi-house-door",
                            ModuleId = 4,
                            Name = "Warehouse Management",
                            Title = "Warehouse Management"
                        },
                        new
                        {
                            Id = 8,
                            Action = "index",
                            Controller = "Item",
                            IconClass = "bi-box-seam",
                            ModuleId = 4,
                            Name = "Item Management",
                            Title = "Item Management"
                        },
                        new
                        {
                            Id = 9,
                            Action = "Create",
                            Controller = "Order",
                            IconClass = "bi-cart-plus",
                            ModuleId = 5,
                            Name = "Create Order",
                            Title = "Order Creation"
                        },
                        new
                        {
                            Id = 10,
                            Action = "index",
                            Controller = "Order",
                            IconClass = "bi-cart-check",
                            ModuleId = 5,
                            Name = "View Orders",
                            Title = "Order Management"
                        },
                        new
                        {
                            Id = 11,
                            Action = "General",
                            Controller = "Settings",
                            IconClass = "bi-gear",
                            ModuleId = 7,
                            Name = "General Settings",
                            Title = "General Settings"
                        },
                        new
                        {
                            Id = 12,
                            Action = "Security",
                            Controller = "Settings",
                            IconClass = "bi-shield",
                            ModuleId = 7,
                            Name = "Security Settings",
                            Title = "Security Settings"
                        },
                        new
                        {
                            Id = 13,
                            Action = "Index",
                            Controller = "Payroll",
                            IconClass = "bi-cash-stack",
                            ModuleId = 6,
                            Name = "Payroll Dashboard",
                            Title = "Payroll Dashboard"
                        },
                        new
                        {
                            Id = 14,
                            Action = "EmployeeSalaries",
                            Controller = "Payroll",
                            IconClass = "bi-wallet",
                            ModuleId = 6,
                            Name = "Employee Salaries",
                            Title = "Employee Salaries"
                        },
                        new
                        {
                            Id = 15,
                            Action = "ProcessSalaries",
                            Controller = "Payroll",
                            IconClass = "bi-calculator",
                            ModuleId = 6,
                            Name = "Salary Processing",
                            Title = "Salary Processing"
                        },
                        new
                        {
                            Id = 16,
                            Action = "Reports",
                            Controller = "Payroll",
                            IconClass = "bi-file-earmark-bar-graph",
                            ModuleId = 6,
                            Name = "Payroll Reports",
                            Title = "Payroll Reports"
                        },
                        new
                        {
                            Id = 17,
                            Action = "Bonuses",
                            Controller = "Payroll",
                            IconClass = "bi-gift",
                            ModuleId = 6,
                            Name = "Bonuses Management",
                            Title = "Bonuses Management"
                        },
                        new
                        {
                            Id = 18,
                            Action = "Deductions",
                            Controller = "Payroll",
                            IconClass = "bi-dash-circle",
                            ModuleId = 6,
                            Name = "Deductions",
                            Title = "Salary Deductions"
                        },
                        new
                        {
                            Id = 19,
                            Action = "Tax",
                            Controller = "Payroll",
                            IconClass = "bi-percent",
                            ModuleId = 6,
                            Name = "Tax Calculations",
                            Title = "Tax Calculations"
                        },
                        new
                        {
                            Id = 20,
                            Action = "GeneratePayslip",
                            Controller = "Payroll",
                            IconClass = "bi-receipt",
                            ModuleId = 6,
                            Name = "Payslip Generation",
                            Title = "Payslip Generation"
                        },
                        new
                        {
                            Id = 21,
                            Action = "Overtime",
                            Controller = "Payroll",
                            IconClass = "bi-clock-history",
                            ModuleId = 6,
                            Name = "Overtime Payments",
                            Title = "Overtime Payments"
                        },
                        new
                        {
                            Id = 22,
                            Action = "History",
                            Controller = "Payroll",
                            IconClass = "bi-archive",
                            ModuleId = 6,
                            Name = "Payroll History",
                            Title = "Payroll History"
                        },
                        new
                        {
                            Id = 23,
                            Action = "Index",
                            Controller = "Accountant",
                            IconClass = "bi-currency-dollar",
                            ModuleId = 8,
                            Name = "Financial Orders",
                            Title = "Financial History"
                        },
                        new
                        {
                            Id = 24,
                            Action = "PreOnboarding",
                            Controller = "Onboarding",
                            IconClass = "bi-person-plus",
                            ModuleId = 9,
                            Name = "Pre-Onboarding",
                            Title = "Pre-Onboarding Process"
                        },
                        new
                        {
                            Id = 25,
                            Action = "ITSetup",
                            Controller = "Onboarding",
                            IconClass = "bi-laptop",
                            ModuleId = 9,
                            Name = "IT Setup",
                            Title = "IT System & Equipment Setup"
                        },
                        new
                        {
                            Id = 26,
                            Action = "Training",
                            Controller = "Onboarding",
                            IconClass = "bi-book",
                            ModuleId = 9,
                            Name = "Training & Orientation",
                            Title = "Employee Training and Orientation"
                        },
                        new
                        {
                            Id = 27,
                            Action = "Clearance",
                            Controller = "Offboarding",
                            IconClass = "bi-door-open",
                            ModuleId = 10,
                            Name = "Exit Clearance",
                            Title = "Employee Exit Clearance"
                        },
                        new
                        {
                            Id = 28,
                            Action = "RevokeAccess",
                            Controller = "Offboarding",
                            IconClass = "bi-lock",
                            ModuleId = 10,
                            Name = "Access Revocation",
                            Title = "Revoke IT & System Access"
                        },
                        new
                        {
                            Id = 29,
                            Action = "FinalPayroll",
                            Controller = "Offboarding",
                            IconClass = "bi-file-earmark-text",
                            ModuleId = 10,
                            Name = "Final Payroll & Documents",
                            Title = "Final Payroll & Document Handling"
                        },
                        new
                        {
                            Id = 30,
                            Action = "Records",
                            Controller = "HR",
                            IconClass = "bi-file-earmark-person",
                            ModuleId = 11,
                            Name = "Employee Records",
                            Title = "Manage Employee Records"
                        },
                        new
                        {
                            Id = 31,
                            Action = "Leave",
                            Controller = "HR",
                            IconClass = "bi-calendar-event",
                            ModuleId = 11,
                            Name = "Leave Management",
                            Title = "Manage Leaves & Absences"
                        },
                        new
                        {
                            Id = 32,
                            Action = "Payroll",
                            Controller = "HR",
                            IconClass = "bi-cash-coin",
                            ModuleId = 11,
                            Name = "Payroll Processing",
                            Title = "Automate Payroll Processing"
                        },
                        new
                        {
                            Id = 33,
                            Action = "Reviews",
                            Controller = "Performance",
                            IconClass = "bi-graph-up",
                            ModuleId = 12,
                            Name = "Performance Reviews",
                            Title = "Employee Performance Reviews"
                        },
                        new
                        {
                            Id = 34,
                            Action = "KPIs",
                            Controller = "Performance",
                            IconClass = "bi-bar-chart-line",
                            ModuleId = 12,
                            Name = "KPI Tracking",
                            Title = "Track KPIs & Goals"
                        },
                        new
                        {
                            Id = 35,
                            Action = "Feedback",
                            Controller = "Performance",
                            IconClass = "bi-chat-left-text",
                            ModuleId = 12,
                            Name = "Feedback & Recognition",
                            Title = "360 Feedback & Recognition"
                        },
                        new
                        {
                            Id = 36,
                            Action = "Tickets",
                            Controller = "ITService",
                            IconClass = "bi-ticket-detailed",
                            ModuleId = 14,
                            Name = "Ticket Management",
                            Title = "Manage IT Support Tickets"
                        },
                        new
                        {
                            Id = 37,
                            Action = "Monitoring",
                            Controller = "ITService",
                            IconClass = "bi-speedometer",
                            ModuleId = 14,
                            Name = "System Monitoring",
                            Title = "Monitor IT Infrastructure"
                        },
                        new
                        {
                            Id = 38,
                            Action = "Inventory",
                            Controller = "ITService",
                            IconClass = "bi-pc-display",
                            ModuleId = 14,
                            Name = "Hardware Inventory",
                            Title = "Manage IT Assets"
                        },
                        new
                        {
                            Id = 39,
                            Action = "Tickets",
                            Controller = "Support",
                            IconClass = "bi-headset",
                            ModuleId = 18,
                            Name = "Support Tickets",
                            Title = "Manage Customer Tickets"
                        },
                        new
                        {
                            Id = 40,
                            Action = "Chat",
                            Controller = "Support",
                            IconClass = "bi-chat-dots",
                            ModuleId = 18,
                            Name = "Live Chat",
                            Title = "Provide Live Chat Support"
                        },
                        new
                        {
                            Id = 41,
                            Action = "FAQ",
                            Controller = "Support",
                            IconClass = "bi-question-circle",
                            ModuleId = 18,
                            Name = "FAQ & Help Center",
                            Title = "Manage Help Center Articles"
                        },
                        new
                        {
                            Id = 42,
                            Action = "Finance",
                            Controller = "Reports",
                            IconClass = "bi-file-earmark-bar-graph",
                            ModuleId = 20,
                            Name = "Financial Reports",
                            Title = "View Financial Reports"
                        },
                        new
                        {
                            Id = 43,
                            Action = "Employees",
                            Controller = "Reports",
                            IconClass = "bi-people",
                            ModuleId = 20,
                            Name = "Employee Insights",
                            Title = "Analyze Employee Performance"
                        },
                        new
                        {
                            Id = 44,
                            Action = "Sales",
                            Controller = "Reports",
                            IconClass = "bi-graph-up",
                            ModuleId = 20,
                            Name = "Sales & Revenue",
                            Title = "Track Sales & Revenue"
                        },
                        new
                        {
                            Id = 45,
                            Action = "Index",
                            Controller = "Support",
                            IconClass = "bi-speedometer2",
                            ModuleId = 18,
                            Name = "Support Dashboard",
                            Title = "View Support Overview"
                        },
                        new
                        {
                            Id = 46,
                            Action = "Index",
                            Controller = "OrderReport",
                            IconClass = "bi-cart",
                            ModuleId = 20,
                            Name = "Orders Dashboard",
                            Title = "View Orders Overview"
                        },
                        new
                        {
                            Id = 47,
                            Action = "Settings",
                            Controller = "ExportImport",
                            IconClass = "bi-download",
                            ModuleId = 7,
                            Name = "Data Management",
                            Title = "Export & Import Settings"
                        },
                        new
                        {
                            Id = 48,
                            Action = "Export",
                            Controller = "ExportImport",
                            IconClass = "bi-file-earmark-arrow-down",
                            ModuleId = 7,
                            Name = "Data Export",
                            Title = "Export "
                        },
                        new
                        {
                            Id = 49,
                            Action = "Import",
                            Controller = "ExportImport",
                            IconClass = "bi-file-earmark-arrow-up",
                            ModuleId = 7,
                            Name = "Data Import",
                            Title = "Import"
                        });
                });

            modelBuilder.Entity("Factory.DAL.Models.Settings.ContractSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ContractEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ContractStartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ContractSettings");
                });

            modelBuilder.Entity("Factory.DAL.Models.Settings.ExportImportSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowNullValues")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CsvDelimiter")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(1)")
                        .HasDefaultValue(",");

                    b.Property<string>("DateFormat")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("yyyy-MM-dd");

                    b.Property<string>("DefaultExportFormat")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("XLSX");

                    b.Property<bool>("EnableExport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("EnableImport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IncludeHeaders")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("MaxExportRows")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10000);

                    b.Property<int>("MaxImportFileSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10485760);

                    b.Property<string>("SupportedExportFormats")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupportedImportFormats")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ValidateImportData")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.ToTable("ExportImportSettings");
                });

            modelBuilder.Entity("Factory.DAL.Models.Settings.NotificationSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("EnableEmailNotifications")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("EnablePushNotifications")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("EnableSmsNotifications")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("NotificationSettings");
                });

            modelBuilder.Entity("Factory.DAL.Models.Support.FAQS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("HelpfulVotes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UnhelpfulVotes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Views")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FAQS");
                });

            modelBuilder.Entity("Factory.DAL.Models.Support.SupportResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("RespondedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ResponseText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SupportTicketId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RespondedByUserId");

                    b.HasIndex("SupportTicketId");

                    b.ToTable("SupportResponse");
                });

            modelBuilder.Entity("Factory.DAL.Models.Support.SupportTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedToUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Medium");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Open");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("General");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.ToTable("SupportTicket");
                });

            modelBuilder.Entity("Factory.DAL.Models.Warehouses.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Dimensions")
                        .IsRequired()
                        .HasPrecision(10, 2)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsFragile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("ManufactureDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SubWarehouseId")
                        .HasColumnType("int");

                    b.Property<string>("Thickness")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubWarehouseId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Items", (string)null);
                });

            modelBuilder.Entity("Factory.DAL.Models.Warehouses.MainWarehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressAr")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AddressEn")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("NameAr")
                        .IsUnique();

                    b.HasIndex("NameEn")
                        .IsUnique();

                    b.ToTable("MainWarehouses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressAr = "الطابق الأول، المصنع أ",
                            AddressEn = "Factory A, Floor 1",
                            NameAr = "المستودع الرئيسي",
                            NameEn = "Main Warehouse"
                        });
                });

            modelBuilder.Entity("Factory.DAL.Models.Warehouses.SubWarehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressAr")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AddressEn")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MainWarehouseId")
                        .HasColumnType("int");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("MainWarehouseId");

                    b.HasIndex("NameAr")
                        .IsUnique();

                    b.HasIndex("NameEn")
                        .IsUnique();

                    b.ToTable("SubWarehouses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressAr = "القسم الأول، المستودع الرئيسي",
                            AddressEn = "Main Warehouse, Section 1",
                            MainWarehouseId = 1,
                            NameAr = "المستودع الفرعي أ",
                            NameEn = "Sub-Warehouse A"
                        },
                        new
                        {
                            Id = 2,
                            AddressAr = "القسم الثاني، المستودع الرئيسي",
                            AddressEn = "Main Warehouse, Section 2",
                            MainWarehouseId = 1,
                            NameAr = "المستودع الفرعي ب",
                            NameEn = "Sub-Warehouse B"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Factory.DAL.Models.OnBoarding.ITSetupModule", b =>
                {
                    b.HasOne("Factory.DAL.Models.OnBoarding.OnboardingProcess", "OnboardingProcess")
                        .WithOne("ITSetup")
                        .HasForeignKey("Factory.DAL.Models.OnBoarding.ITSetupModule", "OnboardingProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OnboardingProcess");
                });

            modelBuilder.Entity("Factory.DAL.Models.OnBoarding.OrientationModule", b =>
                {
                    b.HasOne("Factory.DAL.Models.OnBoarding.OnboardingProcess", "OnboardingProcess")
                        .WithOne("Orientation")
                        .HasForeignKey("Factory.DAL.Models.OnBoarding.OrientationModule", "OnboardingProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OnboardingProcess");
                });

            modelBuilder.Entity("Factory.DAL.Models.OnBoarding.PreboardingModule", b =>
                {
                    b.HasOne("Factory.DAL.Models.OnBoarding.OnboardingProcess", "OnboardingProcess")
                        .WithOne("Preboarding")
                        .HasForeignKey("Factory.DAL.Models.OnBoarding.PreboardingModule", "OnboardingProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OnboardingProcess");
                });

            modelBuilder.Entity("Factory.DAL.Models.OnBoarding.TrainingModule", b =>
                {
                    b.HasOne("Factory.DAL.Models.OnBoarding.OnboardingProcess", "OnboardingProcess")
                        .WithOne("Training")
                        .HasForeignKey("Factory.DAL.Models.OnBoarding.TrainingModule", "OnboardingProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OnboardingProcess");
                });

            modelBuilder.Entity("Factory.DAL.Models.OrderList.OrderItem", b =>
                {
                    b.HasOne("Factory.DAL.Models.OrderList.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Factory.DAL.Models.Permission.RolePermission", b =>
                {
                    b.HasOne("Factory.DAL.Models.Permission.Module", "Module")
                        .WithMany("RolePermissions")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Factory.DAL.Models.Permission.PermissionTyepe", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Factory.DAL.Models.Permission.SubModule", b =>
                {
                    b.HasOne("Factory.DAL.Models.Permission.Module", "Module")
                        .WithMany("SubModules")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Factory.DAL.Models.Support.FAQS", b =>
                {
                    b.HasOne("Factory.DAL.Models.Auth.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Factory.DAL.Models.Support.SupportResponse", b =>
                {
                    b.HasOne("Factory.DAL.Models.Auth.ApplicationUser", "RespondedByUser")
                        .WithMany()
                        .HasForeignKey("RespondedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Factory.DAL.Models.Support.SupportTicket", "SupportTicket")
                        .WithMany("Responses")
                        .HasForeignKey("SupportTicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RespondedByUser");

                    b.Navigation("SupportTicket");
                });

            modelBuilder.Entity("Factory.DAL.Models.Support.SupportTicket", b =>
                {
                    b.HasOne("Factory.DAL.Models.Auth.ApplicationUser", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedToUser");
                });

            modelBuilder.Entity("Factory.DAL.Models.Warehouses.Item", b =>
                {
                    b.HasOne("Factory.DAL.Models.Warehouses.SubWarehouse", "SubWarehouse")
                        .WithMany()
                        .HasForeignKey("SubWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Factory.DAL.Models.Warehouses.MainWarehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SubWarehouse");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Factory.DAL.Models.Warehouses.SubWarehouse", b =>
                {
                    b.HasOne("Factory.DAL.Models.Warehouses.MainWarehouse", "MainWarehouse")
                        .WithMany("SubWarehouses")
                        .HasForeignKey("MainWarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainWarehouse");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Factory.DAL.Models.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Factory.DAL.Models.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Factory.DAL.Models.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Factory.DAL.Models.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Factory.DAL.Models.OnBoarding.OnboardingProcess", b =>
                {
                    b.Navigation("ITSetup")
                        .IsRequired();

                    b.Navigation("Orientation")
                        .IsRequired();

                    b.Navigation("Preboarding")
                        .IsRequired();

                    b.Navigation("Training")
                        .IsRequired();
                });

            modelBuilder.Entity("Factory.DAL.Models.OrderList.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Factory.DAL.Models.Permission.Module", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("SubModules");
                });

            modelBuilder.Entity("Factory.DAL.Models.Permission.PermissionTyepe", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Factory.DAL.Models.Support.SupportTicket", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("Factory.DAL.Models.Warehouses.MainWarehouse", b =>
                {
                    b.Navigation("SubWarehouses");
                });
#pragma warning restore 612, 618
        }
    }
}
